export interface PageSEO {
  slug: string
  keyfocus: string
  title: string
  description: string
  image?: string
  synonyms: string[]
  related: string[]
}

export const seoData: Record<string, PageSEO> = {
  home: {
    slug: '/',
    keyfocus: 'surf school tamarindo',
    title: 'Surf School Tamarindo | Learn to Surf in Costa Rica',
    description: 'Surf school Tamarindo offering beginner-friendly lessons, surf camps, and packages. Learn with certified instructors in Costa Rica. Book Now!',
    image: '/images/surf-school-tamarindo-surf-instructor-student.webp',
    synonyms: ['surf classes tamarindo', 'surf instruction costa rica', 'surf training tamarindo'],
    related: ['Surf School Tamarindo', 'Tamarindo Surf school'],
  },
  surfLessons: {
    slug: '/tamarindo-surf-lessons',
    keyfocus: 'tamarindo surf lessons',
    title: 'Tamarindo Surf Lessons | Learn to Surf in Costa Rica',
    description: 'Book tamarindo surf lessons with certified instructors. Safe, fun & perfect for beginners and families. Private, semi-private & group lessons available.',
    image: '/images/surf-school-tamarindo-beginner-lesson.webp',
    synonyms: ['Surf lessons in Tamarindo', 'Learn to surf Tamarindo', 'Surf classes Tamarindo', 'Tamarindo surfing lessons'],
    related: ['Surf lessons Costa Rica', 'Beginner surf lessons Tamarindo', 'surf school near me Tamarindo'],
  },
  privateLessons: {
    slug: '/private-surf-lessons-cocoa-beach',
    keyfocus: 'private surf lessons Cocoa Beach',
    title: 'Private Surf Lessons Cocoa Beach | One-on-One Surf Coaching',
    description: 'Book private surf lessons in Cocoa Beach, Florida for personalized coaching and faster progress. One-on-one instruction for all levels.',
    image: '/images/private-surf-lessons-tamarindo-one-on-one.webp',
    synonyms: ['Cocoa Beach private surf lesson', 'one-on-one surf lessons Cocoa Beach', 'personalized surf lessons Cocoa Beach', 'private surf classes Cocoa Beach'],
    related: ['surf lessons in Cocoa Beach', 'Cocoa Beach surf school', 'beginner surf lessons Cocoa Beach', 'surf coaching Florida'],
  },
  semiPrivateLessons: {
    slug: '/surf-coaching-cocoa-beach',
    keyfocus: 'surf coaching Cocoa Beach',
    title: 'Surf Coaching Cocoa Beach | Small Group Surf Lessons',
    description: 'Book surf coaching in Cocoa Beach, Florida. Certified instructors, all equipment included, and focused coaching for couples, friends, and small groups.',
    image: '/images/semi-private-surf-tamarindo-wave-riding.webp',
    synonyms: ['small group surf coaching Cocoa Beach', 'couple surf lessons Cocoa Beach', 'surf lessons for couples Cocoa Beach', '2-3 person surf lesson Cocoa Beach'],
    related: ['surf lessons for couples Cocoa Beach', 'small group surf coaching Florida'],
  },
  groupLessons: {
    slug: '/group-surf-lessons-cocoa-beach',
    keyfocus: 'group surf lessons Cocoa Beach',
    title: 'Group Surf Lessons in Cocoa Beach | Learn to Surf Together',
    description: 'Fun and safe group surf lessons in Cocoa Beach, Florida. Perfect for friends, families, and solo travelers. Certified instructors and beginner-friendly waves. Book now!',
    image: '/images/group-surf-lessons-tamarindo-students-beach.webp',
    synonyms: ['group surfing lessons Cocoa Beach', 'surf group lessons Cocoa Beach', 'group surf classes Cocoa Beach', 'surf lessons for groups Cocoa Beach', 'beginner group surf lessons Cocoa Beach'],
    related: ['beginner surf lessons Cocoa Beach', 'surf lessons Cocoa Beach Florida', 'group activities Cocoa Beach Florida'],
  },
  surfPackages: {
    slug: '/tamarindo-surf-packages',
    keyfocus: 'surf packages tamarindo',
    title: 'Surf Packages in Tamarindo | Pura Vida Surf School',
    description: 'Choose from our 3, 5, or 7-day surf packages in Tamarindo. Designed for beginners and intermediate surfers looking for progress and fun.',
    image: '/images/5-days-surf-package-tamarindo-progress.webp',
    synonyms: ['tamarindo surf packages', 'surf package costa rica', 'multi-day surf lessons tamarindo'],
    related: ['surf lessons tamarindo', 'surf camp tamarindo', 'book surf lessons tamarindo'],
  },
  package3Days: {
    slug: '/starter-pack',
    keyfocus: 'starter surf pack Cocoa Beach',
    title: 'Starter Pack Cocoa Beach | 3 Surf Lessons',
    description: 'Start your surfing journey with our Starter Pack in Cocoa Beach. 3 surf lessons, certified instructor, surfboard included. From $245.',
    image: '/images/surf-school-tamarindo-beginner-lesson.webp',
    synonyms: ['starter surf package Cocoa Beach', '3 surf lessons Cocoa Beach', 'beginner surf package Cocoa Beach'],
    related: ['surf packages Cocoa Beach', 'beginner surf lessons Cocoa Beach', 'surf camp Cocoa Beach'],
  },
  package5Days: {
    slug: '/progression-pack',
    keyfocus: 'progression surf pack Cocoa Beach',
    title: 'Progression Pack Cocoa Beach | 5-Day Surf Package',
    description: 'Our most popular Progression Pack in Cocoa Beach. 4 surf lessons plus 1 surf trip, certified instructor, surfboard included. From $405.',
    image: '/images/5-days-surf-package-tamarindo-progress.webp',
    synonyms: ['5 day surf package Cocoa Beach', '5 days surf lessons Cocoa Beach', 'progression surf package'],
    related: ['surf packages Cocoa Beach', 'surf camp Cocoa Beach', 'private surf lessons Cocoa Beach'],
  },
  package7Days: {
    slug: '/elite-pack',
    keyfocus: 'elite surf pack Cocoa Beach',
    title: 'Elite Pack Cocoa Beach | 7-Day Surf Package',
    description: 'Our complete Elite Pack in Cocoa Beach. 6 surf lessons plus 1 surf trip, certified instructor, surfboard included. Full immersion experience from $565.',
    image: '/images/7-days-surf-lessons-tamarindo-green-wave.webp',
    synonyms: ['7 day surf package Cocoa Beach', '7 days surf lessons Cocoa Beach', 'week surf package Cocoa Beach', 'full week surf package Florida'],
    related: ['surf packages Cocoa Beach', 'surf camp Cocoa Beach', 'progression pack Cocoa Beach'],
  },
  surfCamp: {
    slug: '/surf-camp-cocoa-beach',
    keyfocus: 'Cocoa Beach surf camp',
    title: 'Cocoa Beach Surf Camp | Pura Vida Surf School Florida',
    description: 'Stay and surf with our Cocoa Beach surf camp. Daily lessons, certified coaches, surf trips, video analysis, and beginner-friendly Florida waves. Book today!',
    image: '/images/7-days-surf-lessons-tamarindo-green-wave.webp',
    synonyms: ['surf camp Cocoa Beach', 'Cocoa Beach surf retreat', 'surf and stay Cocoa Beach', 'best surf camp in Cocoa Beach', 'surf vacation Cocoa Beach'],
    related: ['surf camp Florida', '7 days surf camp Cocoa Beach', '5 days surf camp Cocoa Beach'],
  },
  surfCamp7Days: {
    slug: '/7-days-surf-camp-tamarindo',
    keyfocus: '7 days surf camp tamarindo',
    title: '7 Days Surf Camp Tamarindo | All-Inclusive Surf Package',
    description: 'Join our 7 days surf camp in Tamarindo. Daily lessons, surf trips, gear, photos, and pura vida vibes. Perfect for beginners and intermediates. Book today!',
    image: '/images/7-days-surf-lessons-tamarindo-green-wave.webp',
    synonyms: ['7 day surf camp costa rica', 'week surf camp tamarindo', 'surf camp one week tamarindo', 'tamarindo 7 days surf vacation'],
    related: ['surf vacations costa rica', 'tamarindo surf packages', 'surf camp tamarindo costa rica', '5 days surf camp tamarindo'],
  },
  surfCamp5Days: {
    slug: '/5-days-surf-camp-tamarindo',
    keyfocus: '5 days surf camp tamarindo',
    title: '5 Days Surf Camp Tamarindo | Surf Package Costa Rica',
    description: 'Book our 5 days surf camp in Tamarindo. Daily lessons, surf trips, gear, photos, and pura vida vibes. Perfect for beginners and intermediates.',
    image: '/images/5-days-surf-package-tamarindo-progress.webp',
    synonyms: ['5 day surf camp costa rica', 'short surf camp tamarindo', 'costa rica 5 day surf vacation', '5 day surf stay tamarindo'],
    related: ['surf camp tamarindo costa rica', '7 days surf camp tamarindo', 'surf packages tamarindo'],
  },
  aboutUs: {
    slug: '/best-surf-school-in-tamarindo',
    keyfocus: 'best surf school in Tamarindo',
    title: 'Best Surf School in Tamarindo | Pura Vida Surf School',
    description: 'Learn why we are the best surf school in Tamarindo. Certified instructors, local experience, and a pura vida approach to teaching. Meet our team today!',
    image: '/images/surf-school-tamarindo-surf-instructor-student.webp',
    synonyms: ['top surf school in tamarindo', 'best surf lessons tamarindo', 'leading surf school in tamarindo', 'best surfing instructors tamarindo', 'pura vida surf school tamarindo'],
    related: ['surf lessons tamarindo costa rica', 'surf instructors tamarindo', 'tamarindo surf camp', 'surf school costa rica'],
  },
  contact: {
    slug: '/surf-school-near-me-tamarindo',
    keyfocus: 'surf school near me Tamarindo',
    title: 'Surf School Near Me Tamarindo | Tamarindo Costa Rica',
    description: 'Looking for a surf school near you in Tamarindo? Contact us to book surf lessons, surf camps, and packages. Quick replies on WhatsApp.',
    image: '/images/surf-school-tamarindo-students.webp',
    synonyms: ['surf school near me costa rica', 'tamarindo surf school near me', 'surf lessons near me tamarindo', 'nearest surf school tamarindo'],
    related: ['tamarindo surf lessons', 'surf school tamarindo costa rica', 'private surf lessons tamarindo', 'book surf lessons tamarindo'],
  },
  bookNow: {
    slug: '/book-now',
    keyfocus: 'book surf lessons tamarindo',
    title: 'Book Surf Lessons & Surf Camps In Tamarindo, Costa Rica',
    description: 'Book your surf lessons, surf packages or surf camp in Tamarindo online. Choose your experience and secure your spot with our professional surf school.',
    image: '/images/surf-school-tamarindo-beginner-lesson.webp',
    synonyms: ['book surf classes tamarindo', 'reserve surf lessons tamarindo', 'surf lesson booking tamarindo'],
    related: ['private surf lessons tamarindo', 'surf packages tamarindo', 'surf camp tamarindo'],
  },
  blog: {
    slug: '/blog',
    keyfocus: 'surf school tamarindo blog',
    title: 'Surf Blog — Tips, Guides & News | Pura Vida Surf School',
    description: 'Read our surf blog for beginner tips, Tamarindo travel guides, surfing techniques, and updates from Pura Vida Surf School in Costa Rica.',
    image: '/images/surf-school-tamarindo-surf-instructor-student.webp',
    synonyms: ['surf tips tamarindo', 'tamarindo surf guide', 'learn to surf blog costa rica'],
    related: ['surf school tamarindo', 'surf lessons tamarindo', 'tamarindo travel guide'],
  },
  bestTimeSurf: {
    slug: '/blog/best-time-to-surf-tamarindo',
    keyfocus: 'best time to surf tamarindo',
    title: 'Best Time to Surf in Tamarindo | Month-by-Month Guide',
    description: 'Discover the best time to surf in Tamarindo, Costa Rica. Month-by-month breakdown of swell, wind, and crowd conditions from local instructors.',
    image: '/images/surf-school-tamarindo-surf-instructor-student.webp',
    synonyms: ['tamarindo surf season', 'when to surf tamarindo', 'tamarindo waves by month', 'surf season costa rica'],
    related: ['surf lessons tamarindo', 'surf camp tamarindo', 'tamarindo travel guide'],
  },
  firstSurfLesson: {
    slug: '/blog/what-to-expect-first-surf-lesson-tamarindo',
    keyfocus: 'first surf lesson tamarindo',
    title: 'What to Expect on Your First Surf Lesson in Tamarindo',
    description: "Nervous about your first surf lesson in Tamarindo? Here's exactly what happens from the moment you arrive to catching your first wave. No experience needed.",
    image: '/images/surf-school-tamarindo-beginner-lesson.webp',
    synonyms: ['beginner surf lesson tamarindo', 'first time surfing tamarindo', 'learn to surf tamarindo beginners'],
    related: ['private surf lessons tamarindo', 'group surf lessons tamarindo', 'surf school tamarindo'],
  },
  familySurfLessons: {
    slug: '/family-surf-lessons-tamarindo',
    keyfocus: 'family surf lessons tamarindo',
    title: 'Family Surf Lessons Tamarindo | Surf with Your Kids in Costa Rica',
    description: 'Fun and safe family surf lessons in Tamarindo for kids and adults. Certified instructors, patient teaching, and unforgettable waves. Book your family session!',
    image: '/images/family-surf-lessons-tamarindo.webp',
    synonyms: ['surf lessons for families tamarindo', 'kids surf lessons tamarindo', 'family surfing tamarindo', 'surf lessons with kids costa rica'],
    related: ['group surf lessons tamarindo', 'beginner surf lessons tamarindo', 'surf camp tamarindo'],
  },
  tideChart: {
    slug: '/tamarindo-tide-chart',
    keyfocus: 'tamarindo tide chart',
    title: 'Tamarindo Tide Chart 2026 | Surf Tide Times Costa Rica',
    description: 'Tamarindo tide chart for surfers. Check tide times, learn which tides produce the best waves, and plan your surf session with our local guide.',
    image: '/images/surf-school-tamarindo-surf-instructor-student.webp',
    synonyms: ['tamarindo tides', 'tamarindo tide times', 'costa rica tide chart', 'tamarindo surf tides', 'tide chart tamarindo beach'],
    related: ['tamarindo surf lessons', 'best time to surf tamarindo', 'surf school tamarindo'],
  },
  sanJoseToTamarindo: {
    slug: '/blog/how-to-get-from-san-jose-to-tamarindo',
    keyfocus: 'how to get from san jose to tamarindo',
    title: 'How to Get from San José to Tamarindo | Transport Guide 2026',
    description: 'Complete guide on how to get from San José to Tamarindo, Costa Rica. Compare shuttle, rental car, and bus options — times, costs, and tips from locals.',
    image: '/images/student-from-our-surf-school-in-Tamarindo.webp',
    synonyms: ['san jose to tamarindo', 'tamarindo transportation', 'getting to tamarindo costa rica', 'san jose tamarindo shuttle'],
    related: ['tamarindo surf lessons', 'surf camp tamarindo', 'tamarindo travel guide'],
  },
  tamarindoVsJaco: {
    slug: '/blog/tamarindo-vs-jaco-surf-beginners',
    keyfocus: 'tamarindo vs jaco surf',
    title: 'Tamarindo vs Jacó for Beginner Surfers | Which Is Better?',
    description: 'Tamarindo or Jacó? We compare both surf destinations for beginner surfers — waves, crowds, infrastructure, and vibe. Find out which is right for you.',
    image: '/images/surf-school-tamarindo-beginner-lesson.webp',
    synonyms: ['tamarindo vs jaco surfing', 'best beginner surf spot costa rica', 'jaco vs tamarindo beach', 'where to learn surf costa rica'],
    related: ['tamarindo surf lessons', 'private surf lessons tamarindo', 'surf school tamarindo'],
  },
  packingList: {
    slug: '/blog/surf-trip-costa-rica-packing-list',
    keyfocus: 'surf trip costa rica packing list',
    title: 'Surf Trip Packing List: What to Bring to Costa Rica',
    description: 'Complete packing list for a surf trip to Costa Rica. Gear, clothing, and documents — everything you need for Tamarindo in one guide.',
    image: '/images/student-from-our-surf-school-in-Tamarindo.webp',
    synonyms: ['what to pack for surf trip costa rica', 'costa rica surf packing list', 'tamarindo packing list', 'surf vacation packing guide'],
    related: ['tamarindo surf lessons', 'surf camp tamarindo', 'surf packages tamarindo'],
  },
  isTamarindoGoodForBeginners: {
    slug: '/blog/is-tamarindo-good-for-beginner-surfers',
    keyfocus: 'is tamarindo good for beginner surfers',
    title: 'Is Tamarindo Good for Beginner Surfers? | Honest Local Guide',
    description: "Wondering if Tamarindo is the right place to learn surfing? We break down the waves, conditions, and why it is one of Costa Rica's best spots for first-timers.",
    image: '/images/surf-school-tamarindo-beginner-lesson.webp',
    synonyms: ['tamarindo beginner surf', 'learn to surf tamarindo', 'tamarindo surfing for beginners', 'is tamarindo safe to surf'],
    related: ['group surf lessons tamarindo', 'private surf lessons tamarindo', 'surf school tamarindo'],
  },
  surfingWithKids: {
    slug: '/blog/surfing-with-kids-tamarindo',
    keyfocus: 'surfing with kids tamarindo',
    title: 'Surfing with Kids in Tamarindo | Family Surf Guide Costa Rica',
    description: 'Everything parents need to know about surfing with kids in Tamarindo. Best age to start, safety tips, gear, and what to expect from a family surf lesson.',
    image: '/images/family-surf-lessons-tamarindo.webp',
    synonyms: ['kids surfing tamarindo', 'family surf costa rica', 'surf lessons for children tamarindo', 'can kids surf tamarindo'],
    related: ['family surf lessons tamarindo', 'group surf lessons tamarindo', 'surf camp tamarindo'],
  },
  whatIsSurfCamp: {
    slug: '/blog/what-is-a-surf-camp',
    keyfocus: 'what is a surf camp',
    title: 'What Is a Surf Camp? Everything You Need to Know',
    description: 'Curious about surf camps? We explain what a surf camp is, what to expect, who they are for, and why Tamarindo is one of the best places to do one in Costa Rica.',
    image: '/images/7-days-surf-lessons-tamarindo-green-wave.webp',
    synonyms: ['surf camp explained', 'surf camp vs surf lessons', 'surf camp costa rica beginner', 'surf retreat tamarindo'],
    related: ['surf camp tamarindo', '7-days-surf-camp-tamarindo', '5-days-surf-camp-tamarindo'],
  },
}

export const ROUTES = {
  HOME: '/',
  SURF_LESSONS: '/tamarindo-surf-lessons',
  PRIVATE: '/private-surf-lessons-cocoa-beach',
  SEMI_PRIVATE: '/surf-coaching-cocoa-beach',
  GROUP: '/group-surf-lessons-cocoa-beach',
  PACKAGES: '/tamarindo-surf-packages',
  PKG_3: '/starter-pack',
  PKG_5: '/progression-pack',
  PKG_7: '/elite-pack',
  CAMP: '/surf-camp-cocoa-beach',
  CAMP_7: '/7-days-surf-camp-tamarindo',
  CAMP_5: '/5-days-surf-camp-tamarindo',
  ABOUT: '/best-surf-school-in-tamarindo',
  CONTACT: '/surf-school-near-me-tamarindo',
  BOOK: '/book-now',
}
